## Basic Imports for Testing

In [2]:
import os
import finnhub
import pandas as pd
import json
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv())
api_key = os.getenv('FINNHUB_API_KEY')

# Setup client
finnhub_client = finnhub.Client(api_key=api_key)

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

## Free Plan Endpoints

In [48]:
# Basic financials
## print(finnhub_client.company_basic_financials('AAPL', 'all'))
all_df = pd.DataFrame(finnhub_client.company_basic_financials('AAPL', 'all'))
all_df

,metric,metricType,series,symbol
10DayAverageTradingVolume,41.00093,all,NaN,AAPL
13WeekPriceReturnDaily,-7.5499,all,NaN,AAPL
26WeekPriceReturnDaily,5.2931,all,NaN,AAPL
3MonthADReturnStd,23.376865,all,NaN,AAPL
3MonthAverageTradingVolume,46.56376,all,NaN,AAPL
52WeekHigh,288.62,all,NaN,AAPL
52WeekHighDate,2025-12-03,all,NaN,AAPL
52WeekLow,169.2101,all,NaN,AAPL
52WeekLowDate,2025-04-08,all,NaN,AAPL
52WeekPriceReturnDaily,14.0035,all,NaN,AAPL
5DayPriceReturnDaily,0.6802,all,NaN,AAPL
assetTurnoverAnnual,1.1584,all,NaN,AAPL
assetTurnoverTTM,1.2435,all,NaN,AAPL
beta,1.116114,all,NaN,AAPL
bookValuePerShareAnnual,4.991,all,NaN,AAPL
bookValuePerShareQuarterly,5.9982,all,NaN,AAPL
bookValueShareGrowth5Y,5.34,all,NaN,AAPL
capexCagr5Y,11.71,all,NaN,AAPL
cashFlowPerShareAnnual,6.6855,all,NaN,AAPL
cashFlowPerShareQuarterly,8.3878,all,NaN,AAPL
cashFlowPerShareTTM,6.86253,all,NaN,AAPL
cashPerSharePerShareAnnual,3.7024,all,NaN,AAPL
cashPerSharePerShareQuarterly,4.5507,all,NaN,AAPL
currentDividendYieldTTM,0.4183,all,NaN,AAPL
currentEv/freeCashFlowAnnual,37.9367,all,NaN,AAPL
currentEv/freeCashFlowTTM,30.3825,all,NaN,AAPL
currentRatioAnnual,0.8933,all,NaN,AAPL
currentRatioQuarterly,0.9737,all,NaN,AAPL
dividendGrowthRate5Y,4.95,all,NaN,AAPL
dividendIndicatedAnnual,1.04,all,NaN,AAPL
dividendPerShareAnnual,1.0318,all,NaN,AAPL
dividendPerShareTTM,1.0413,all,NaN,AAPL
dividendYieldIndicatedAnnual,0.413289,all,NaN,AAPL
ebitdPerShareAnnual,9.6255,all,NaN,AAPL
ebitdPerShareTTM,10.2536,all,NaN,AAPL
ebitdaCagr5Y,13.33,all,NaN,AAPL
ebitdaInterimCagr5Y,8.45,all,NaN,AAPL
enterpriseValue,3746894.5,all,NaN,AAPL
epsAnnual,7.465,all,NaN,AAPL
epsBasicExclExtraItemsAnnual,7.465,all,NaN,AAPL
epsBasicExclExtraItemsTTM,7.9038,all,NaN,AAPL
epsExclExtraItemsAnnual,7.465,all,NaN,AAPL
epsExclExtraItemsTTM,7.9038,all,NaN,AAPL
epsGrowth3Y,6.89,all,NaN,AAPL
epsGrowth5Y,17.91,all,NaN,AAPL
epsGrowthQuarterlyYoy,18.54,all,NaN,AAPL
epsGrowthTTMYoy,25.65,all,NaN,AAPL
epsInclExtraItemsAnnual,7.465,all,NaN,AAPL
epsInclExtraItemsTTM,7.9038,all,NaN,AAPL
epsNormalizedAnnual,7.465,all,NaN,AAPL
epsTTM,7.9038,all,NaN,AAPL
evEbitdaTTM,24.4927,all,NaN,AAPL
evRevenueTTM,8.6014,all,NaN,AAPL
focfCagr5Y,6.13,all,NaN,AAPL
forwardPE,29.792367,all,NaN,AAPL
grossMargin5Y,44.47,all,NaN,AAPL
grossMarginAnnual,46.91,all,NaN,AAPL
grossMarginTTM,47.33,all,NaN,AAPL
inventoryTurnoverAnnual,33.9834,all,NaN,AAPL
inventoryTurnoverTTM,35.8924,all,NaN,AAPL
longTermDebt/equityAnnual,1.0623,all,NaN,AAPL
longTermDebt/equityQuarterly,0.8695,all,NaN,AAPL
marketCapitalization,3701702.5,all,NaN,AAPL
monthToDatePriceReturnDaily,-4.7468,all,NaN,AAPL
netIncomeEmployeeAnnual,0.6748,all,NaN,AAPL
netIncomeEmployeeTTM,0.7095,all,NaN,AAPL
netInterestCoverageAnnual,622.5082,all,NaN,AAPL
netInterestCoverageTTM,622.5082,all,NaN,AAPL
netMarginGrowth5Y,5.18,all,NaN,AAPL
netProfitMargin5Y,25.48,all,NaN,AAPL
netProfitMarginAnnual,26.92,all,NaN,AAPL
netProfitMarginTTM,27.04,all,NaN,AAPL
operatingMargin5Y,30.67,all,NaN,AAPL
operatingMarginAnnual,31.97,all,NaN,AAPL
operatingMarginTTM,32.38,all,NaN,AAPL
payoutRatioAnnual,13.77,all,NaN,AAPL
payoutRatioTTM,13.15,all,NaN,AAPL
pb,41.9742,all,NaN,AAPL
pbAnnual,50.978,all,NaN,AAPL
pbQuarterly,45.8689,all,NaN,AAPL
pcfShareAnnual,33.2045,all,NaN,AAPL
pcfShareTTM,27.3245,all,NaN,AAPL
peAnnual,33.048,all,NaN,AAPL
peBasicExclExtraTTM,31.4298,all,NaN,AAPL
peExclExtraAnnual,30.96975,all,NaN,AAPL
peExclExtraTTM,31.4298,all,NaN,AAPL
peInclExtraTTM,31.4298,all,NaN,AAPL
peNormalizedAnnual,33.048,all,NaN,AAPL
peTTM,31.4298,all,NaN,AAPL
pegTTM,1.241309,all,NaN,AAPL
pfcfShareAnnual,37.4791,all,NaN,AAPL
pfcfShareTTM,30.0161,all,NaN,AAPL
pretaxMargin5Y,30.64,all,NaN,AAPL
pretaxMarginAnnual,31.89,all,NaN,AAPL
pretaxMarginTTM,32.4,all,NaN,AAPL
priceRelativeToS&P50013Week,-4.107,all,NaN,AAPL
priceRelativeToS&P50026Week,6.2033,all,NaN,AAPL
priceRelativeToS&P5004Week,-2.4712,all,NaN,AAPL
priceRelativeToS&P50052Week,0.2249,all,NaN,AAPL
priceRelativeToS&P500Ytd,-3.2231,all,NaN,AAPL
psAnnual,8.8949,all,NaN,AAPL
psTTM,8.4976,all,NaN,AAPL
ptbvAnnual,4.8643,all,NaN,AAPL
ptbvQuarterly,6.4066,all,NaN,AAPL
quickRatioAnnual,0.8588,all,NaN,AAPL
quickRatioQuarterly,0.9376,all,NaN,AAPL
receivablesTurnoverAnnual,11.3725,all,NaN,AAPL
receivablesTurnoverTTM,12.5249,all,NaN,AAPL
revenueEmployeeAnnual,2.507,all,NaN,AAPL
revenueEmployeeTTM,2.6242,all,NaN,AAPL
revenueGrowth3Y,1.81,all,NaN,AAPL
revenueGrowth5Y,8.68,all,NaN,AAPL
revenueGrowthQuarterlyYoy,15.65,all,NaN,AAPL
revenueGrowthTTMYoy,10.07,all,NaN,AAPL
revenuePerShareAnnual,27.7354,all,NaN,AAPL
revenuePerShareTTM,29.413,all,NaN,AAPL
revenueShareGrowth5Y,12.11,all,NaN,AAPL
roa5Y,27.93,all,NaN,AAPL
roaRfy,31.18,all,NaN,AAPL
roaTTM,33.62,all,NaN,AAPL
roe5Y,163.92,all,NaN,AAPL
roeRfy,151.91,all,NaN,AAPL
roeTTM,159.94,all,NaN,AAPL
roi5Y,57.1,all,NaN,AAPL
roiAnnual,64.51,all,NaN,AAPL
roiTTM,68.92,all,NaN,AAPL
tangibleBookValuePerShareAnnual,5.8583,all,NaN,AAPL
tangibleBookValuePerShareQuarterly,6.7916,all,NaN,AAPL
tbvCagr5Y,11.34,all,NaN,AAPL
totalDebt/totalEquityAnnual,1.3547,all,NaN,AAPL
totalDebt/totalEquityQuarterly,1.0263,all,NaN,AAPL
yearToDatePriceReturnDaily,-7.4377,all,NaN,AAPL
annual,NaN,all,"{'bookValue': [{'period': '2025-09-27', 'v': 7...",AAPL
quarterly,NaN,all,"{'assetTurnoverTTM': [{'period': '2025-12-27',...",AAPL

In [54]:
all_df_copy = all_df.copy(deep=True)
annual_pre_df = pd.DataFrame(all_df.loc['annual']).iloc[-2:,:].T.set_index('symbol')
quarterly_df = pd.DataFrame(all_df.loc['quarterly'])
## annual_df = all_df_copy.at['annual',['series','symbol']]
## annual_df = annual_pre_df[['series','symbol']]
## annual_df = pd.DataFrame(annual_pre_df.loc['series'])
## annual_bookvalue_df = annual_pre_df.set_index('symbol')
annual_pre_df
## quarterly_df

                                                   series
symbol
AAPL    {'bookValue': [{'period': '2025-09-27', 'v': 7...

In [4]:
# Earnings surprises
## print(finnhub_client.company_earnings('AAPL', limit=5))
df = pd.DataFrame(finnhub_client.company_earnings('TSLA', limit=5))
df

,actual,estimate,period,quarter,surprise,surprisePercent,symbol,year
0,0.50,0.4559,2025-12-31,4,0.0441,9.6732,TSLA,2025
1,0.50,0.5586,2025-09-30,3,-0.0586,-10.4905,TSLA,2025
2,0.40,0.4373,2025-06-30,2,-0.0373,-8.5296,TSLA,2025
3,0.27,0.3990,2025-03-31,1,-0.1290,-32.3308,TSLA,2025

In [ ]:
# Company News
# Need to use _from instead of from to avoid conflict
print(finnhub_client.company_news('AAPL', _from="2026-03-16", to="2026-03-20"))

In [ ]:
# Company Peers
print(finnhub_client.company_peers('AAPL'))

In [ ]:
# Company Profile 2
print(finnhub_client.company_profile2(symbol='AAPL'))

In [ ]:
# List country
print(finnhub_client.country())

In [ ]:
# Crypto Exchange
print(finnhub_client.crypto_exchanges())

In [ ]:
# Crypto symbols
print(finnhub_client.crypto_symbols('BINANCE'))

In [ ]:
# Financials as reported
print(finnhub_client.financials_reported(symbol='AAPL', freq='annual'))

In [ ]:
# Forex exchanges
print(finnhub_client.forex_exchanges())

In [ ]:
# Forex symbols
print(finnhub_client.forex_symbols('OANDA'))

In [3]:
# General news
print(finnhub_client.general_news('forex', min_id=0))

[{'category': 'forex', 'datetime': 1774371820, 'headline': 'The U.S. Treasury sold $69 billion of 2 year notes at a high yield of 3.936%', 'id': 7690496, 'image': '', 'related': '', 'source': 'Forexlive', 'summary': '<p>The US treasury sold $69 billion of 2 year notes at a high yield of 3.936%</p><ul><li>WI level at the time of the auction 3.918%</li><li>Tail 1.8 basis points vs 6 month average of -0.2 basis points</li><li>Bid to cover 2.44X vs 6 month average of 2.62X</li><li>Directs 16.5% versus 6 month average of 32.1%</li><li>Indirects 59.3% versus 6 month average of 57.2%</li><li>Dealers 24.12% versus 6 month average of 10.7%</li></ul><p>AUCTION GRADE: D-</p><p>It would take a failed auction to get an F grade but the D grade is pretty low relative to recent auctions. The only saving grace is the Indirect take of 59.3% which was higher than 57.2% but that may just because the directs were so weak at only 16.5%.  Dealers were saddled with nearly 25%.</p><p>The 2 year yield is currently trading at 3.95% up 12.2 basis points. The 10 year yield is up 8.3 basis points at 4.419%. The recent high reached 4.44%. </p>\n                            This article was written by Greg Michalowski at investinglive.com.', 'url': 'https://investinglive.com/news/the-us-treasury-sold-69-billion-of-2-year-notes-at-a-high-yield-of-3926-20260324/'}]

In [ ]:
# IPO calendar
print(finnhub_client.ipo_calendar(_from="2020-05-01", to="2020-06-01"))

In [2]:
# Quote
print(finnhub_client.quote('AAPL'))

{'c': 252.63, 'd': 1.14, 'dp': 0.4533, 'h': 254.825, 'l': 249.55, 'o': 251.14999999999998, 'pc': 251.49, 't': 1774374168}

In [ ]:
# Recommendation trends
print(finnhub_client.recommendation_trends('AAPL'))

In [ ]:
# Stock symbols
print(finnhub_client.stock_symbols('US')[0:5])

In [ ]:
# Earnings Calendar
print(finnhub_client.earnings_calendar(_from="2026-03-16", to="2026-03-20", symbol="AAPL", international=False))

In [ ]:
# Covid-19
print(finnhub_client.covid19())

In [ ]:
# FDA Calendar
print(finnhub_client.fda_calendar())

In [ ]:
# Symbol lookup
print(finnhub_client.symbol_lookup('apple'))

In [ ]:
# Visa application
print(finnhub_client.stock_visa_application("AAPL", "2021-01-01", "2022-06-15"))

In [ ]:
# Insider sentiment
print(finnhub_client.stock_insider_sentiment('AAPL', '2021-01-01', '2022-03-01'))

In [ ]:
# USA Spending
print(finnhub_client.stock_usa_spending("LMT", "2021-01-01", "2022-06-15"))

In [ ]:
## Market Holday / Status
print(finnhub_client.market_holiday(exchange='US'))
print(finnhub_client.market_status(exchange='US'))

## Paid Endpoints

# Aggregate Indicators
print(finnhub_client.aggregate_indicator('AAPL', 'D'))

# EPS estimates
print(finnhub_client.company_eps_estimates('AMZN', freq='quarterly'))

# Company Executives
print(finnhub_client.company_executive('AAPL'))

# Company Profile
print(finnhub_client.company_profile(symbol='AAPL'))
print(finnhub_client.company_profile(isin='US0378331005'))
print(finnhub_client.company_profile(cusip='037833100'))

# Revenue Estimates
print(finnhub_client.company_revenue_estimates('TSLA', freq='quarterly'))

# Economic data
print(finnhub_client.economic_data('MA-USA-656880'))

# Filings
print(finnhub_client.filings(symbol='AAPL', _from="2020-01-01", to="2020-06-11"))

# Financials
print(finnhub_client.financials('AAPL', 'bs', 'annual'))

# Forex all pairs
print(finnhub_client.forex_rates(base='USD'))

# Fund Ownership
print(finnhub_client.fund_ownership('AMZN', limit=5))

# Investors ownership
print(finnhub_client.ownership('AAPL', limit=5))

# Major developments
print(finnhub_client.press_releases('AAPL', _from="2020-01-01", to="2020-12-31"))

# News sentiment
print(finnhub_client.news_sentiment('AAPL'))

# Pattern recognition
print(finnhub_client.pattern_recognition('AAPL', 'D'))

# Price target
print(finnhub_client.price_target('AAPL'))

# Stock dividends
print(finnhub_client.stock_dividends('KO', _from='2019-01-01', to='2020-01-01'))

# Stock dividends 2
print(finnhub_client.stock_basic_dividends("KO"))

# Transcripts
print(finnhub_client.transcripts('AAPL_162777'))

# Transcripts list
print(finnhub_client.transcripts_list('AAPL'))

# Upgrade downgrade
print(finnhub_client.upgrade_downgrade(symbol='AAPL', _from='2020-01-01', to='2020-06-30'))

# Economic code
print(finnhub_client.economic_code()[0:5])

# Economic calendar
print(finnhub_client.calendar_economic('2021-01-01', '2021-01-07'))

# Support resistance
print(finnhub_client.support_resistance('AAPL', 'D'))

# Technical Indicator
print(finnhub_client.technical_indicator(symbol="AAPL", resolution='D', _from=1583098857, to=1584308457, indicator='rsi', indicator_fields={"timeperiod": 3}))

# Stock splits
print(finnhub_client.stock_splits('AAPL', _from='2000-01-01', to='2020-01-01'))

# Forex candles
print(finnhub_client.forex_candles('OANDA:EUR_USD', 'D', 1590988249, 1591852249))

# Crypto Candles
print(finnhub_client.crypto_candles('BINANCE:BTCUSDT', 'D', 1590988249, 1591852249))

# Tick Data
print(finnhub_client.stock_tick('AAPL', '2020-03-25', 500, 0))

# BBO Data
print(finnhub_client.stock_nbbo("AAPL", "2020-03-25", 500, 0))

# Indices Constituents
print(finnhub_client.indices_const(symbol = "^GSPC"))

# Indices Historical Constituents
print(finnhub_client.indices_hist_const(symbol = "^GSPC"))

# ETFs Profile
print(finnhub_client.etfs_profile('SPY'))
print(finnhub_client.etfs_profile(isin="US78462F1030"))

# ETFs Holdings
print(finnhub_client.etfs_holdings('SPY'))
print(finnhub_client.etfs_holdings(isin="US00214Q1040", skip=2))
print(finnhub_client.etfs_holdings("IPO", date='2022-03-10'))

# ETFs Sector Exposure
print(finnhub_client.etfs_sector_exp('SPY'))

# ETFs Country Exposure
print(finnhub_client.etfs_country_exp('SPY'))

# International Filings
print(finnhub_client.international_filings('RY.TO'))
print(finnhub_client.international_filings(country='GB'))

# SEC Sentiment Analysis
print(finnhub_client.sec_sentiment_analysis('0000320193-20-000052'))

# SEC similarity index
print(finnhub_client.sec_similarity_index('AAPL'))

# Bid Ask
print(finnhub_client.last_bid_ask('AAPL'))

# Insider transactions
print(finnhub_client.stock_insider_transactions('AAPL', '2021-01-01', '2021-03-01'))

# Mutual Funds Profile
print(finnhub_client.mutual_fund_profile("VTSAX"))
print(finnhub_client.mutual_fund_profile(isin="US9229087286"))

# Mutual Funds Holdings
print(finnhub_client.mutual_fund_holdings("VTSAX"))
print(finnhub_client.mutual_fund_holdings(isin="US9229087286", skip=2))

# Mutual Funds Sector Exposure
print(finnhub_client.mutual_fund_sector_exp("VTSAX"))

# Mutual Funds Country Exposure
print(finnhub_client.mutual_fund_country_exp("VTSAX"))

# Revenue breakdown
print(finnhub_client.stock_revenue_breakdown('AAPL'))

# Social sentiment
print(finnhub_client.stock_social_sentiment('GME'))

# Investment Themes
print(finnhub_client.stock_investment_theme('financialExchangesData'))

# Supply chain
print(finnhub_client.stock_supply_chain('AAPL'))

# Company ESG
print(finnhub_client.company_esg_score("AAPL"))

# Earnings Quality Score
print(finnhub_client.company_earnings_quality_score('AAPL', 'quarterly'))

# Crypto Profile
print(finnhub_client.crypto_profile('BTC'))

# EBITDA Estimates
print(finnhub_client.company_ebitda_estimates("TSLA", freq="quarterly"))

# EBIT Estimates
print(finnhub_client.company_ebit_estimates("TSLA", freq="quarterly"))

# USPTO Patent
print(finnhub_client.stock_uspto_patent("AAPL", "2021-01-01", "2021-12-31"))

# Bond Profile
print(finnhub_client.bond_profile(isin='US912810TD00'))

# Bond price
print(finnhub_client.bond_price('US912810TD00', 1590988249, 1649099548))

# Lobbying
print(finnhub_client.stock_lobbying("AAPL", "2021-01-01", "2022-06-15"))

# Sector metrics
print(finnhub_client.sector_metric('NA'))

# Fund's EET data
print(finnhub_client.mutual_fund_eet('LU2036931686'))
print(finnhub_client.mutual_fund_eet_pai('LU2036931686'))

# Symbol & ISIN change
print(finnhub_client.isin_change(_from='2022-10-01', to='2022-10-07'))
print(finnhub_client.symbol_change(_from='2022-10-01', to='2022-10-07'))

# 13-F data
print(finnhub_client.institutional_profile())
print(finnhub_client.institutional_portfolio(cik='1000097', _from='2022-01-01', to='2022-10-07'))
print(finnhub_client.institutional_ownership('TSLA', '', _from='2022-01-01', to='2022-10-07'))

# Bond yield and FINRA Trace tick
print(finnhub_client.bond_yield_curve('10y'))
print(finnhub_client.bond_tick('US693475BF18', '2022-08-19', 500, 0, 'trace'))

# Congressional Trading
print(finnhub_client.congressional_trading('AAPL', '2020-01-01', '2023-03-31'))

# Price metrics with historical data
print(finnhub_client.price_metrics(symbol="AAPL", date="2022-01-01"))

# Bank Branch
print(finnhub_client.bank_branch("JPM"))